### ISSUE TITLE
LDAP account errors are not logged

### ISSUE THREAD

**Issue by davidmc24** [commercehub-oss/dropwizard-auth-ms-ad#12]
If a `javax.naming.AuthenticationException` is thrown due to password expired, account disabled, etc., the root cause of this is not available in the logs.  The raw exception looked something like this: `javax.naming.AuthenticationException: [LDAP: error code 49 - 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 532, v1db1`

**Comment by mhurne** [comment]
@davidmc24 -- looks like @gavinhogan fixed this back on Oct 21, 2014. Do you agree?

**Comment by davidmc24** [comment]
Yes, it appears fixed.
